package com.falon.habit.weight.presentation.model

import com.falon.habit.weight.domain.model.WeightHistory

data class WeightHistoryViewState(
    val weightHistory: WeightHistory?,
    val weight: String,
    val weightError: Boolean,
    val weightErrorMessage: String,
    val fat: String,
    val fatError: Boolean,
    val fatErrorMessage: String,
    val muscle: String,
    val muscleError: Boolean,
    val muscleErrorMessage: String,
    val water: String,
    val waterError: Boolean,
    val waterErrorMessage: String,
    val bmi: String,
    val bmiError: Boolean,
    val bmiErrorMessage: String,
    val bones: String,
    val bonesError: Boolean,
    val bonesErrorMessage: String,
    val weightGoal: String,
    val weightGoalError: Boolean,
    val weightGoalErrorMessage: String,
    val fatGoal: String,
    val fatGoalError: Boolean,
    val fatGoalErrorMessage: String,
    val muscleGoal: String,
    val muscleGoalError: Boolean,
    val muscleGoalErrorMessage: String,
    val waterGoal: String,
    val waterGoalError: Boolean,
    val waterGoalErrorMessage: String,
    val bmiGoal: String,
    val bmiGoalError: Boolean,
    val bmiGoalErrorMessage: String,
    val bonesGoal: String,
    val bonesGoalError: Boolean,
    val bonesGoalErrorMessage: String,
)
